source 'https://rubygems.org'
ruby '2.1.2'

gem 'sinatra', '~> 1.4.5'
gem 'slim', '~> 2.0.3'

group :test do
  gem 'rspec', '~> 3.1.0'
  gem 'capybara', '~> 2.3.0'
  gem 'simplecov', '~> 0.9.0', require: false
end

group :development do
  gem 'guard-rspec', '~> 4.3.1'
end